obstacle_range: 2.0
raytrace_range: 5.0
robot_radius: 0.22
inflation_radius: 0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan sonar_scan_sensor
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
sonar_scan_sensor:
    data_type: PointCloud2
    topic: /sonar_cloudpoint
    marking: true
    clearing: true
    # min_obstacle_height: 0.11
    # max_obstacle_height: 0.2
    observation_persistence: 0.0
    expected_update_rate: 0
sonar_layer:
  enabled:            true
  clear_threshold:    0.6
  mark_threshold:     0.8
  topics: ["/sonar0", "/sonar1", "/sonar2", "/sonar3"]
  clear_on_max_reading: true

